"""Generic, dataset-driven chart builders for specification components.

Charts are produced from authoritative rows plus the component's field mapping.
No chart code is ever generated by a model.
"""

from __future__ import annotations

from typing import Any

from app.rendering.charts import (
    AMBER,
    CARD_BG,
    GRID,
    INK,
    MUTED,
    RED,
    STEEL,
    TEAL,
    TEAL_SOFT,
    _fig_to_png,
)
from app.rendering.spec.base import category_labels, numeric, series_values

COLOR_MAP: dict[str, str] = {
    "teal": TEAL,
    "red": RED,
    "amber": AMBER,
    "steel": STEEL,
    "muted": MUTED,
}

_CYCLE = (TEAL, STEEL, AMBER, RED)


def _plt():
    import matplotlib.pyplot as plt

    return plt


def _series_colors(series: list[Any]) -> list[str]:
    colors: list[str] = []
    for idx, item in enumerate(series):
        name = getattr(item, "color", None)
        colors.append(COLOR_MAP.get(name or "", _CYCLE[idx % len(_CYCLE)]))
    return colors


def _empty(message: str, *, width: float = 7.2, height: float = 2.6) -> bytes:
    plt = _plt()
    fig, ax = plt.subplots(figsize=(width, height))
    ax.text(0.5, 0.5, message, ha="center", va="center", color=MUTED, fontsize=10)
    ax.axis("off")
    return _fig_to_png(fig)


def _finish(ax, *, title: str | None, y_label: str | None) -> None:
    if title:
        ax.set_title(title, fontsize=11, color=INK, pad=10)
    if y_label:
        ax.set_ylabel(y_label)
    ax.spines[["top", "right"]].set_visible(False)
    ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)


def bar_chart(
    rows: list[dict[str, Any]],
    *,
    x: str,
    series: list[Any],
    title: str | None = None,
    y_label: str | None = None,
    orientation: str = "vertical",
    stacked: bool = False,
) -> bytes:
    if not rows:
        return _empty("No data for this chart")
    plt = _plt()
    labels = category_labels(rows, x)
    colors = _series_colors(series)
    values = [series_values(rows, item.field) for item in series]

    if orientation == "horizontal":
        height = max(2.6, 0.4 * len(labels) + 1.2)
        fig, ax = plt.subplots(figsize=(7.2, height))
        positions = range(len(labels))
        if stacked or len(series) == 1:
            left = [0.0] * len(labels)
            for idx, item in enumerate(series):
                ax.barh(list(positions), values[idx], left=left, color=colors[idx], label=item.label, height=0.62)
                left = [left[i] + values[idx][i] for i in range(len(labels))]
        else:
            width = 0.8 / len(series)
            for idx, item in enumerate(series):
                offset = (idx - (len(series) - 1) / 2) * width
                ax.barh(
                    [p + offset for p in positions],
                    values[idx],
                    height=width,
                    color=colors[idx],
                    label=item.label,
                )
        ax.set_yticks(list(positions))
        ax.set_yticklabels(labels, fontsize=8)
        ax.invert_yaxis()
        if title:
            ax.set_title(title, fontsize=11, color=INK, pad=8)
        if y_label:
            ax.set_xlabel(y_label)
        ax.spines[["top", "right"]].set_visible(False)
        ax.xaxis.grid(True, color=GRID, linewidth=0.8)
        ax.set_axisbelow(True)
        if len(series) > 1:
            ax.legend(frameon=False, fontsize=8)
        return _fig_to_png(fig)

    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    positions = list(range(len(labels)))
    if stacked:
        bottom = [0.0] * len(labels)
        for idx, item in enumerate(series):
            ax.bar(positions, values[idx], bottom=bottom, color=colors[idx], label=item.label, edgecolor="none")
            bottom = [bottom[i] + values[idx][i] for i in range(len(labels))]
    else:
        width = 0.8 / max(1, len(series))
        for idx, item in enumerate(series):
            offset = (idx - (len(series) - 1) / 2) * width
            ax.bar(
                [p + offset for p in positions],
                values[idx],
                width=width,
                color=colors[idx],
                label=item.label,
                edgecolor="none",
            )
    ax.set_xticks(positions)
    ax.set_xticklabels(labels, fontsize=8)
    if len(labels) > 8:
        for label in ax.get_xticklabels():
            label.set_rotation(30)
            label.set_ha("right")
    _finish(ax, title=title, y_label=y_label)
    if len(series) > 1:
        ax.legend(frameon=False, fontsize=8)
    return _fig_to_png(fig)


def line_chart(
    rows: list[dict[str, Any]],
    *,
    x: str,
    series: list[Any],
    title: str | None = None,
    y_label: str | None = None,
    area: bool = True,
) -> bytes:
    if not rows:
        return _empty("No trend data yet")
    plt = _plt()
    labels = category_labels(rows, x)
    colors = _series_colors(series)
    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    peak = 0.0
    for idx, item in enumerate(series):
        values = series_values(rows, item.field)
        peak = max(peak, max(values) if values else 0.0)
        ax.plot(labels, values, color=colors[idx], marker="o", linewidth=2, markersize=4, label=item.label)
        if area and len(series) == 1:
            ax.fill_between(range(len(values)), values, color=colors[idx], alpha=0.12)
    ax.set_ylim(0, max(1.0, peak * 1.25))
    _finish(ax, title=title, y_label=y_label)
    if len(series) > 1:
        ax.legend(frameon=False, fontsize=8)
    if len(labels) > 8:
        for label in ax.get_xticklabels():
            label.set_rotation(30)
            label.set_ha("right")
    return _fig_to_png(fig)


def pie_chart(
    rows: list[dict[str, Any]],
    *,
    label_field: str,
    value_field: str,
    title: str | None = None,
    donut: bool = False,
) -> bytes:
    values = [numeric(row.get(value_field)) for row in rows]
    if not rows or sum(values) <= 0:
        return _empty("No data for this chart", width=5.4, height=3.2)
    plt = _plt()
    labels = category_labels(rows, label_field)
    colors = [_CYCLE[i % len(_CYCLE)] for i in range(len(labels))]
    fig, ax = plt.subplots(figsize=(5.8, 3.6))
    ax.pie(
        values,
        labels=labels,
        colors=colors,
        autopct="%1.0f%%",
        startangle=90,
        textprops={"fontsize": 8, "color": INK},
        wedgeprops={"width": 0.42} if donut else None,
    )
    ax.axis("equal")
    if title:
        ax.set_title(title, fontsize=11, color=INK, pad=10)
    return _fig_to_png(fig)


def progress_chart(
    rows: list[dict[str, Any]],
    *,
    label_field: str,
    value_field: str,
    target_field: str,
    title: str | None = None,
) -> bytes:
    if not rows:
        return _empty("No progress data")
    plt = _plt()
    labels = category_labels(rows, label_field)
    actual = [numeric(row.get(value_field)) for row in rows]
    target = [numeric(row.get(target_field)) for row in rows]
    height = max(2.4, 0.55 * len(labels) + 1.0)
    fig, ax = plt.subplots(figsize=(7.2, height))
    positions = list(range(len(labels)))
    ax.barh(positions, target, color=CARD_BG, edgecolor=GRID, height=0.55)
    ax.barh(positions, actual, color=TEAL, edgecolor="none", height=0.55)
    for idx, (done, plan) in enumerate(zip(actual, target)):
        pct = round(100.0 * done / plan, 1) if plan else 0.0
        ax.text(
            max(done, plan) * 1.02 + 0.5,
            idx,
            f"{done:,.0f} / {plan:,.0f} ({pct:g}%)",
            va="center",
            fontsize=8,
            color=INK,
        )
    ax.set_yticks(positions)
    ax.set_yticklabels(labels, fontsize=9)
    ax.invert_yaxis()
    ax.set_xlim(0, max([*actual, *target, 1]) * 1.35)
    if title:
        ax.set_title(title, fontsize=11, color=INK, pad=8)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    return _fig_to_png(fig)


def kpi_strip(items: list[tuple[str, str]], *, title: str | None = None) -> bytes:
    """Rendered KPI band used by the PDF/DOCX outputs where HTML uses cards."""
    if not items:
        return _empty("No metrics", width=7.2, height=1.2)
    plt = _plt()
    fig = plt.figure(figsize=(7.4, 1.35 if not title else 1.6))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    if title:
        ax.text(0.01, 0.93, title, fontsize=9.5, color=TEAL, fontweight="bold", va="top")
    count = len(items)
    width = 1.0 / count
    for idx, (label, value) in enumerate(items):
        cx = idx * width + width / 2
        ax.text(cx, 0.52, value, fontsize=16, fontweight="bold", color=INK, ha="center", va="center")
        ax.text(cx, 0.18, label, fontsize=7.5, color=MUTED, ha="center", va="center")
        if idx:
            ax.plot([idx * width, idx * width], [0.1, 0.8], color=TEAL_SOFT, linewidth=0.6, alpha=0.5)
    return _fig_to_png(fig, dpi=150)
