"""Size limits applied to any Report Specification before execution."""

from __future__ import annotations

MAX_SECTIONS = 12
MAX_COMPONENTS_PER_SECTION = 20
MAX_COMPONENTS_TOTAL = 60
MAX_DATA_SOURCES_PER_SPEC = 20
MAX_TABLE_COLUMNS = 12
MAX_TABLE_ROWS = 500
MAX_CHART_SERIES = 4
MAX_CHART_POINTS = 60
MAX_KPI_ITEMS = 8
MAX_NARRATIVE_WORDS = 400
MAX_TITLE_CHARS = 200
MAX_TEXT_CHARS = 4000
MAX_INSTRUCTION_CHARS = 1000
