"""initial_schema

Revision ID: 082fb2cb4010
Revises: 
Create Date: 2026-08-06 16:31:37.047363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082fb2cb4010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('project_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(), nullable=False),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False),
    sa.Column('smtp_from_name', sa.String(), nullable=False),
    sa.Column('smtp_from_email', sa.String(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_connected', sa.Boolean(), nullable=False),
    sa.Column('smtp_last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('daily_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_report_time', sa.String(), nullable=False),
    sa.Column('daily_report_timezone', sa.String(), nullable=False),
    sa.Column('daily_report_recipients', sa.JSON(), nullable=False),
    sa.Column('daily_report_last_sent_on', sa.String(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_provider', sa.String(), nullable=False),
    sa.Column('ai_api_key', sa.String(), nullable=False),
    sa.Column('ai_base_url', sa.String(), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.Column('ai_temperature', sa.Float(), nullable=False),
    sa.Column('ai_max_tokens', sa.Integer(), nullable=False),
    sa.Column('ai_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('report_logo_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_index('studies_name_idx', ['name'], unique=False)

    op.create_table('report_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('last_sent_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_size_kb', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('kobo_server_url', sa.String(), nullable=False),
    sa.Column('kobo_token_encrypted', sa.Text(), nullable=False),
    sa.Column('kobo_username', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id')
    )
    op.create_table('study_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'code', name='study_tools_study_code_uidx')
    )
    with op.batch_alter_table('study_tools', schema=None) as batch_op:
        batch_op.create_index('study_tools_study_idx', ['study_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('form_count', sa.Integer(), nullable=False),
    sa.Column('enumerator_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('last_edited_by', sa.String(), nullable=True),
    sa.Column('current_version_number', sa.Integer(), nullable=True),
    sa.Column('deployed_version_number', sa.Integer(), nullable=True),
    sa.Column('form_version_id', sa.String(), nullable=True),
    sa.Column('deployed_version_id', sa.String(), nullable=True),
    sa.Column('form_definition', sa.JSON(), nullable=True),
    sa.Column('last_submission_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('kobo_date_modified', sa.DateTime(), nullable=True),
    sa.Column('sync_watermark', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('label_language', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('study_tool_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_tool_id'], ['study_tools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('projects_last_sync_idx', ['last_sync_at'], unique=False)
        batch_op.create_index('projects_status_idx', ['status'], unique=False)
        batch_op.create_index('projects_study_idx', ['study_id'], unique=False)
        batch_op.create_index('projects_study_tool_idx', ['study_tool_id'], unique=False)

    op.create_table('report_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'project_id', name='report_projects_report_project_uidx')
    )
    op.create_table('rule_packs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('pack', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kobo_id', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=False),
    sa.Column('enumerator', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'kobo_id', name='submissions_project_kobo_id_uidx')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('submissions_project_idx', ['project_id'], unique=False)
        batch_op.create_index('submissions_submitted_at_idx', ['submitted_at'], unique=False)

    op.create_table('dqa_flags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'rule_id', name='dqa_flags_submission_rule_uidx')
    )
    with op.batch_alter_table('dqa_flags', schema=None) as batch_op:
        batch_op.create_index('dqa_flags_project_idx', ['project_id'], unique=False)
        batch_op.create_index('dqa_flags_severity_idx', ['severity'], unique=False)
        batch_op.create_index('dqa_flags_submission_idx', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dqa_flags', schema=None) as batch_op:
        batch_op.drop_index('dqa_flags_submission_idx')
        batch_op.drop_index('dqa_flags_severity_idx')
        batch_op.drop_index('dqa_flags_project_idx')

    op.drop_table('dqa_flags')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('submissions_submitted_at_idx')
        batch_op.drop_index('submissions_project_idx')

    op.drop_table('submissions')
    op.drop_table('rule_packs')
    op.drop_table('report_projects')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('projects_study_tool_idx')
        batch_op.drop_index('projects_study_idx')
        batch_op.drop_index('projects_status_idx')
        batch_op.drop_index('projects_last_sync_idx')

    op.drop_table('projects')
    with op.batch_alter_table('study_tools', schema=None) as batch_op:
        batch_op.drop_index('study_tools_study_idx')

    op.drop_table('study_tools')
    op.drop_table('study_credentials')
    op.drop_table('reports')
    op.drop_table('report_schedules')
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index('studies_name_idx')

    op.drop_table('studies')
    op.drop_table('settings')
    op.drop_table('prompts')
    op.drop_table('insights')
    # ### end Alembic commands ###
